-- Household Manager — Stage 3 schema
-- Run once in the Supabase dashboard: Project -> SQL Editor -> New query -> paste -> Run

create table household_info (
    id bigint generated by default as identity primary key,
    category text not null,
    title text not null,
    content text,
    updated_at timestamptz not null default now()
);

create table todo_lists (
    id bigint generated by default as identity primary key,
    name text not null
);

create table todo_items (
    id bigint generated by default as identity primary key,
    list_id bigint not null references todo_lists (id) on delete cascade,
    text text not null,
    tag text,
    is_done boolean not null default false,
    created_at timestamptz not null default now()
);

create table grocery_items (
    id bigint generated by default as identity primary key,
    name text not null,
    quantity text,
    added_by text,
    is_checked boolean not null default false
);

create table meal_plan (
    id bigint generated by default as identity primary key,
    date date not null,
    meal_name text not null,
    notes text,
    ingredients text,  -- one ingredient per line; feeds "add to grocery list"
    source_url text     -- recipe link the ingredients were scraped from
);

create table inventory (
    id bigint generated by default as identity primary key,
    item_name text not null,
    purchase_date date,
    warranty_expiry date,
    serial_number text,
    notes text
);

create table notes (
    id bigint generated by default as identity primary key,
    title text not null,
    body text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
